services:
  hashcraft:
    image: hashcraft
    restart: always
  depends_on:
      - mariadb
  networks:
      - mysql-phpmyadmin
  mariadb:
    platform: linux/x86_64
    image: mariadb
    volumes:
      - /mnt/SysHDD/hashcraft-mariadb:/var/lib/mysql
    restart: always
    ports:
      - "3305:3306"
    env_file:
      - db.env
    networks:
      - mysql-phpmyadmin
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    env_file:
      - db.env
    networks:
      - mysql-phpmyadmin

networks:
  mysql-phpmyadmin: