volumes:
  mariadb:
    driver: local

networks:
    db:
        driver: bridge
services:
  botdb:
    image: mariadb
    restart: unless-stopped
    ports:
      - '3305:3305'
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=root
     - MYSQL_PASSWORD=password
    volumes:
      - /hashcraft/db:/var/lib/hashcraft-mysql
    networks:
      db:
  phpmyadmin:
    image: phpmyadmin
    container_name: hashcraft-phpmyadmin
    depends_on:
      - botdb
    restart: always
    ports:
      - 8081:80
    environment:
      - PMA_HOST=botdb
      - PMA_PORT=3306 
    networks:
      db:
  hashcraft:
    image: hashcraft
    restart: always