services:
  # Database
  mariadb:
    platform: linux/x86_64
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: yourdb
      MYSQL_USER: root
      MYSQL_PASSWORD: password
    networks:
      - mariadb-phpmyadmin

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: mariadb
      MYSQL_ROOT_PASSWORD: password
    networks:
      - mariadb-phpmyadmin

networks:
  mariadb-phpmyadmin:

volumes:
  db_data: