services:
  mariadb:
    platform: linux/x86_64
    image: mariadb
    volumes:
      - /mnt/SysHDD/mariadb:/var/lib/mysql
    restart: always
    ports:
      - "3305:3306"
    env_file:
      - db.env
    networks:
      mysql-phpmyadmin:
        ipv4_address: 172.20.128.1
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    env_file:
      - db.env
    networks:
      mysql-phpmyadmin:
        ipv4_address: 172.20.128.2
  hashcraft:
    image: hashcraft
    restart: always
    depends_on:
      - mariadb
    ports:
      - "8091:8091"
    networks:
      mysql-phpmyadmin:
        ipv4_address: 172.20.128.3

networks:
  mysql-phpmyadmin:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1