volumes:
  hashcraftmariadb:
    driver: local

networks:
    db:
        driver: bridge
services:
  botdb:
    image: mariadb
    restart: unless-stopped
    expose:
      - '3305'
    ports:
      - '3305:3305'
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_USER=root
     - MYSQL_PASSWORD=password
     - MYSQL_TCP_PORT=3305
     - MYSQL_DATABASE=mydb
    volumes:
      - hashcraftmariadb:/var/lib/hashcraft-mysql
    networks:
      db:
  phpmyadmin:
    image: phpmyadmin
    container_name: hashcraft-phpmyadmin
    depends_on:
      - botdb
    restart: always
    expose:
      - '8081'
    ports:
      - '8081:80'
    environment:
      - PMA_HOST=botdb
      - PMA_PORT=3305 
    networks:
      db:
  hashcraft:
    image: hashcraft
    restart: always