services:
  botdb:
    image: mariadb
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --skip-log-bin --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    volumes:
      - botdb:/var/lib/hashcraft-mysql
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8081:81
    environment:
      - PMA_ARBITRARY=1
  hashcraft:
    image: hashcraft
    restart: always