env_file:
 - .env
services:
  mariadb:
    platform: linux/x86_64
    image: mariadb
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    ports:
      - "3305:3306"
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    networks:
      - mariadb-phpmyadmin
  phpmyadmin:
    depends_on:
      - mariadb
    image: phpmyadmin
    restart: always
    ports:
      - "8090:80"
    environment:
      PMA_HOST: '${PMA_HOST}'
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
    networks:
      - mariadb-phpmyadmin

networks:
  mariadb-phpmyadmin:

volumes:
  db_data: