volumes:
  mariadb:
    driver: local

networks:
    db:
        driver: bridge
services:
  botdb:
    image: mariadb
    restart: unless-stopped
    ports:
      - '3305:3305'
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_ROOT_PASSWORD_HERE
      MYSQL_USER:  YOUR_MYSQL_USER_HERE 
      MYSQL_PASSWORD: YOUR_USER_PW_HERE
    volumes:
      - /hashcraft/db:/var/lib/hashcraft-mysql
    networks:
      db:
  phpmyadmin:
    image: phpmyadmin
    container_name: hashcraft-phpmyadmin
    depends_on:
      - botdb
    restart: always
    ports:
      - 8081:80
    env_file:
      - .env
    environment:
      - PMA_HOST=botdb
    networks:
      db:
  hashcraft:
    image: hashcraft
    restart: always