services:
  botdb:
    image: mariadb
    container_name: hashcraft-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --skip-log-bin --innodb-file-per-table=1 --skip-innodb-read-only-compressed
    ports:
      - '3305:3305'
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - db-data:/var/lib/hashcraft-mysql
    env_file:
      - .env
  phpmyadmin:
    image: phpmyadmin
    container_name: hashcraft-phpmyadmin
    depends_on:
      - botdb
    restart: always
    ports:
      - 8081:80
    volumes:
      - db-data:
    env_file:
      - .env
    environment:
      - PMA_HOST: botdb
      - MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      - MYSQL_USER: '${MYSQL_USER}'
      - MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
  hashcraft:
    image: hashcraft
    restart: always